name: Upload Python Package to PyPI when a Release is Created

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/iu2frl-civ
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies and build package
        run: |
          python -m venv venv
          source ./venv/bin/activate
          pip install --upgrade pip
          pip install -r ./requirements.txt
          pip install setuptools wheel build click incremental
          python -m incremental.update iu2frl-civ --newversion=${{ steps.get-latest-tag.outputs.tag }}
          python -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1